name: Build LaTeX Document
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '**/Makefile'
      - 'Assets/**'
  pull_request:
    paths-ignore:
        - '**/README.md'
        - '**/LICENSE'
        - '**/.gitignore'
        - '**/.gitattributes'
        - '**/Makefile'
        - 'Assets/**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Repository
        uses: actions/checkout@v4
      - name: LaTeX Document Compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: IPLeiriaMain.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./Configurations/Fonts/*.ttf
            ./Configurations/Fonts/*.otf